### ISSUE TITLE
Mark an conversation on a diff as resolved

### ISSUE THREAD

**Issue by mehulkar** [isaacs/github#251]
Github does a great job of marking and collapsing "outdated diffs" when new commits are made on a PR. Sometimes comments and conversations on diffs are resolved without new commits, however. It would be nice to be able to mark a conversation as resolved to reduce clutter from the PR page.

**Comment by garemoko** [comment]
+1.  Or specifically unresolved.

**Comment by dylanpyle** [comment]
+1

**Comment by FreakTheMighty** [comment]
:+1:

**Comment by diogocp** [comment]
:+1:

**Comment by kubasub** [comment]
:+1:

**Comment by sudotliu** [comment]
:+1:

**Comment by 304NotModified** [comment]
:+1:

**Comment by SilverFire** [comment]
:+1:

**Comment by danaucpe** [comment]
:+1:

**Comment by wbeard** [comment]
:+1:

**Comment by danepowell** [comment]
:+1:

**Comment by tafid** [comment]
:+1:

**Comment by hiqsol** [comment]
:+1:

**Comment by Besedin86** [comment]
:+1:

**Comment by jslee02** [comment]
:+1:

**Comment by albertogasparin** [comment]
:+1:

**Comment by tborychowski** [comment]
:+1:

**Comment by sudoprime** [comment]
:+1:

**Comment by lukeyeager** [comment]
:+1:

**Comment by csudcy** [comment]
:+1: (and another :+1: for specifically unresolve a comment)

**Comment by richardwhatever** [comment]
:+1:

**Comment by lexwraith** [comment]
![image](https://cloud.githubusercontent.com/assets/2289157/15125163/728e8596-15f9-11e6-9c88-fa642453e02d.png)
Yes please.

**Comment by BlaineAtAffirm** [comment]
👍 The new Pull request review updates were nice, but I think this addition would have made it more valuable as comments can now be even harder to sort through

**Comment by regnarock** [comment]
:+1:

**Comment by lintusj1** [comment]
:+1:

**Comment by jeanmonod** [comment]
👍

**Comment by Introvertuous** [comment]
:+1:

**Comment by uramoto-isid** [comment]
:+1:
 It's hard to track status only with reaction icons.

**Comment by cifkao** [comment]
:+1:

**Comment by uramoto-isid** [comment]
+1 
It's too hard to track status only with reaction icons.

**Comment by tpendragon** [comment]
:+1:

**Comment by mpeng-okta** [comment]
👍

**Comment by Lepthy** [comment]
👍

**Comment by tjohnell-handy** [comment]
👍

**Comment by jkieberking** [comment]
👍

**Comment by harsjain** [comment]
👍

**Comment by adbharadwaj** [comment]
👍

**Comment by fwilhe** [comment]
Coming from Gitlab, it is hard to believe that Github does not have this feature.

**Comment by libreoscar** [comment]
👍

**Comment by mocanuserghei** [comment]
:+1:

**Comment by AlecBenzer** [comment]
Please don't reply to an issue just to say '+1': it sends a notification to everyone subscribed to the issue. Instead, just react to the issue's initial comment with the 👍 emoji.


<img width="233" alt="plus_1_github" src="https://user-images.githubusercontent.com/92369/31297680-0455e07c-aab5-11e7-81dc-d6070ca75378.png">

**Comment by aspiers** [comment]
Worth mentioning that https://reviewable.io/ offers a solution to this in its UI.

**Comment by aspiers** [comment]
I have just discovered that GitHub made this possible in April!  However they did a bad job of advertising it, because [their blog announcement](https://blog.github.com/2018-04-18-new-tools-for-open-source-maintainers/) lumped it in with the same mechanism for marking comments as off-topic, misleading, or offensive, and they [documented it under the umbrella of "disruptive comments"](https://help.github.com/articles/managing-disruptive-comments/), even though there is nothing malicious or disruptive about comments which were resolved either through constructive discussion or due to changes being pushed to the PR to address those comments.

Nonetheless, this works reasonably well, and the awesome [https://github.com/sindresorhus/refined-github](refined-github) browser extension even added [a feature to convert it into a UI which doesn't suck](https://github.com/sindresorhus/refined-github/issues/1396).

**Comment by JanZerebecki** [comment]
That still doesn't let you easily see comments on lines that were changed by further commits that are not resolved. The element hiding Outdated is on a different, higher level than the one hiding resolved or manually hidden comments. There is also no option to mark comments as not Outdated.

As both resolved and not resolved comments are hidden by Outdated this doesn't help with reviews that get changes and discussion.

**Comment by aspiers** [comment]
You're correct, but you're talking about a different issue to this one.  This issue is purely about the ability to mark a diff as resolved, and GitHub now provides that.

The issue of not being able to easily get a good handle on which comments are still unresolved is a separate (albeit very important) issue.  If there is not an issue filed in this tracker about that then I warmly encourage you to submit it.  Or if you find it, please link to it.

**Comment by aspiers** [comment]
Actually with further thought, I retract what I said yesterday.  This issue is about having the ability to mark a *conversation* on a diff resolved, but GitHub has only provided  marking *a single comment* as resolved.  This is not nearly as good, because if a conversation on a diff contains 10 comments, the only way to mark the whole conversation as resolved is to manually mark all 10 comments as resolved.  And since this mechanism relies on hiding the comments, if you only hid (say) 7 of those comments, you'd typically end up with a nonsensical discussion of 3 comments which were missing a lot of context.

So GitHub really needs to do better here.  Note that GitLab already offers this, plus *way* more:

https://docs.gitlab.com/ee/user/discussions/index.html#marking-a-comment-or-discussion-as-resolved

**Comment by aspiers** [comment]
This issue only highlights one of the many gaps in GitHub's discussion resolution tracking. I've filed #1314 to highlight the others.

**Comment by AlecBenzer** [comment]
> Sometimes comments and conversations on diffs are resolved without new commits, however.

Note worthing this applies in the other direction too: just because the line was changed doesn't mean the comment was addressed.

**Comment by rmacklin** [comment]
I'm seeing this live on GitHub today:

![screen shot 2018-08-29 at 11 40 33 am](https://user-images.githubusercontent.com/1863540/44808165-6268d080-ab80-11e8-8fc3-922a53c5be73.png)

However, I've yet to see anything on the GitHub changelog about it. Perhaps it's only released to a subset of users? Are others here seeing it?

**Comment by aspiers** [comment]
Interesting!  Yes I'm seeing it too.  Let's hope they document it properly at some point.

**Comment by agdespopoulos** [comment]
I'm seeing it too. Loving it.

**Comment by tjohnell-handy** [comment]
Yep, this is officially resolved! ✌️ everyone.

/unsubscribe

**Comment by aspiers** [comment]
Well, technically speaking based on the exact nature of the issue description above, yes you're right - it's officially resolved.  However, [as I noted in sindresorhus/refined-github#1056](https://github.com/sindresorhus/refined-github/issues/1056#issuecomment-418342052), this is only half the story.

The other part GitHub needs to implement to make this really useful is to make it clearer in the UI which comments are resolved and which ones still need resolving.  For comparison, look at how [the Gerrit developers already started to implement this quite a while ago](https://youtu.be/WsPhoPGUsss?t=9m47s), although IIUC it won't be available until [Gerrit 2.16](https://www.gerritcodereview.com/2.16.html) is released.

**Comment by mehulkar** [comment]
woot!

**Comment by aspiers** [comment]
[**@rmacklin**](https://github.com/rmacklin) commented on [29 Aug 2018, 19:41 BST](https://github.com/isaacs/github/issues/251#issuecomment-417061602 "2018-08-29T18:41:45Z - Replied by Github Reply Comments"):
> However, I've yet to see anything on the GitHub changelog about it. Perhaps it's only released to a subset of users? Are others here seeing it?

GitHub [recently told us](https://github.com/isaacs/github/issues/1314#issuecomment-426487616) that [they have officially announced this feature](https://blog.github.com/changelog/2018-08-31-resolvable-conversations/).  I'm guessing that it took a while to announce because they were using us power users as guinea pigs before releasing to all users :-)
