### ISSUE TITLE
[meta] Move all of isaacs/github issues to platform.github.community

### ISSUE THREAD

**Issue by erlend-sh** [isaacs/github#924]
There is an official channel for all of this feedback now, which is https://platform.github.community

It'd be a lot easier to track GitHub feature requests if isaacs/github was discontinued in favour of the official Platform Forum. You could coordinate with the GitHub team to move all issues over by using this tool:

https://meta.discourse.org/t/introducing-github-issues-to-discourse/46671?u=erlend_sh

**Comment by Mottie** [comment]
It's not official for "all of this feedback"... the blue notification at the top of the landing pages states the following:

> Welcome! The GitHub Platform Forum is a place to discuss our Platform Early Access programs: the GitHub GraphQL API, and our new Integrations feature.
>
> If you have questions about GitHub in general (not related to our Platform), or if you're looking for support for the official GitHub API v3, please contact support.

**Comment by cirosantilli** [comment]
But they also promised a "Community Forum", likely hosted on the same platform, that will address everything: https://github.com/blog/2256-a-whole-new-github-universe-announcing-new-tools-forums-and-features

**Comment by TPS** [comment]
Still, this doesn't seem like this is structured to implement #6.…  We'll see if it grows into it.

**Comment by aspiers** [comment]
[**@TPS**](https://github.com/TPS) commented on [March 10, 2019 2:30 PM](https://github.com/isaacs/github/issues/924#issuecomment-471311245 "2019-03-10T14:30:01Z - Replied by Github Reply Comments"):
> Still, this doesn't seem like this is structured to implement [#6](https://github.com/isaacs/github/issues/6).… We'll see if it grows into it.

I agree that GitHub Community is currently unusable as an issue tracker.  It's designed as a discussion forum, not a vehicle for tracking issues and driving them to resolution.  In particular:

- It's divided into "Conversations" and "Original Series".
  - "Conversations" is full of people asking for help with tasks which don't reflect any issue with GitHub's design or implementation.  If we merged real issues with GitHub into this forum, the issues would get drowned out by the noise.
  - "Original series" seems to be read-only series of articles. 
- There's no clear strategy for avoiding posting of duplicates.
- The taxonomy under Conversations is coarse-grained and strictly hierarchical.  In contrast, this issue tracker has fine-grained tags and each issue can have multiple tags.
- Issues can be assigned to people; community conversations cannot.

**Comment by aspiers** [comment]
Based on the above I suggest closing this for now. Any objections?

**Comment by cmbkla** [comment]
You also cannot use the word "suggestion" or "feature" in a post at all, so it seems like it isn't a great place to **suggest** changes to **features**

**Comment by TPS** [comment]
It seems that https://github.com/github/roadmap is *closer* to what the community expects from GitHub than that Discourse site.  But every single issue is locked to GitHub collaborators only, so effectively read-only to everyone else!

**Comment by TPS** [comment]
https://github.com/github/feedback _does_ feels more like GitHub than the still-awkward [GitHub.Community](https://GitHub.Community) Discourse site, though it currently geared toward to just 3 beta products).  Still, _this_ issue remains unknowable @ this point.

**Comment by TPS** [comment]
Per https://github.com/isaacs/github/issues/1985, this repo will be eventually handled via https://github.com/github/feedback.

**Comment by Levi-Lesches** [comment]
In the spirit of "moving issues from one place to another", would it be a good idea for someone on the GH team to write a bot that moves issues to the new discussions? In #1985 they say they wanted to open it before doing that, so I think now would be a good time. 

To avoid overflowing the new repo, the bot could only copy issues with more than a certain threshold of 👍, avoid copying "+1" comments, etc.

**Comment by TPS** [comment]
I think that would be a _brilliant_ idea to bring up @ #1985, as there's evidently  reluctance to _move_ any issues to the new location.

**Comment by TPS** [comment]
Ohhh, @Levi-Lesches, maybe *that'*s what's meant by "migration qualifiers" in #1985?!  _Please_ do replicate your suggestion there! 🙇🏾‍♂️

**Comment by Levi-Lesches** [comment]
Thanks!

**Comment by TPS** [comment]
@Levi-Lesches Of course, you're welcome! 🙇🏾‍♂️ N.B.:  I modified your idea a touch to include links to the existing docs re: converting issues → discussions, in hopes it'd spark more hope/ideas.
